-- Compatible avec les deux tables de la premiere version Hibernate.
CREATE TABLE IF NOT EXISTS articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference VARCHAR(60) NOT NULL UNIQUE,
    nom VARCHAR(150) NOT NULL,
    unite VARCHAR(40) NOT NULL,
    quantite BIGINT NOT NULL,
    seuil_alerte BIGINT NOT NULL,
    version BIGINT
);
CREATE TABLE IF NOT EXISTS mouvements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL REFERENCES articles(id),
    type VARCHAR(255) NOT NULL,
    quantite BIGINT NOT NULL,
    stock_apres BIGINT NOT NULL,
    responsable VARCHAR(150) NOT NULL,
    motif VARCHAR(500),
    date TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_mouvement_article_date ON mouvements(article_id, date);
