ALTER TABLE articles ADD COLUMN actif BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE articles ADD CONSTRAINT ck_article_quantite CHECK (quantite >= 0);
ALTER TABLE articles ADD CONSTRAINT ck_article_seuil CHECK (seuil_alerte >= 0);
ALTER TABLE mouvements ADD CONSTRAINT ck_mouvement_quantite CHECK (quantite > 0);
ALTER TABLE mouvements ADD CONSTRAINT ck_mouvement_stock CHECK (stock_apres >= 0);
ALTER TABLE mouvements ADD CONSTRAINT ck_mouvement_type CHECK (type IN ('ENTREE', 'SORTIE'));

CREATE TABLE utilisateurs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant VARCHAR(80) NOT NULL UNIQUE,
    nom VARCHAR(150) NOT NULL,
    mot_de_passe VARCHAR(100) NOT NULL,
    role VARCHAR(30) NOT NULL CHECK (role IN ('ADMIN','GESTIONNAIRE','LECTEUR')),
    actif BOOLEAN NOT NULL DEFAULT TRUE,
    echecs_connexion INTEGER NOT NULL DEFAULT 0,
    bloque_jusqua TIMESTAMP WITH TIME ZONE
);
CREATE TABLE sessions_acces (
    empreinte VARCHAR(64) PRIMARY KEY,
    utilisateur_id BIGINT NOT NULL REFERENCES utilisateurs(id),
    expiration TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_session_utilisateur ON sessions_acces(utilisateur_id);
CREATE INDEX idx_session_expiration ON sessions_acces(expiration);

ALTER TABLE mouvements ADD COLUMN utilisateur_id BIGINT REFERENCES utilisateurs(id);
ALTER TABLE mouvements ADD COLUMN beneficiaire VARCHAR(150);
CREATE INDEX idx_mouvement_date ON mouvements(date);

CREATE TABLE alertes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL REFERENCES articles(id),
    cree_le TIMESTAMP WITH TIME ZONE NOT NULL,
    resolue_le TIMESTAMP WITH TIME ZONE,
    acquittee_le TIMESTAMP WITH TIME ZONE,
    acquittee_par BIGINT REFERENCES utilisateurs(id)
);
CREATE INDEX idx_alerte_article ON alertes(article_id, resolue_le);
INSERT INTO alertes(article_id, cree_le)
SELECT id, CURRENT_TIMESTAMP FROM articles WHERE quantite <= seuil_alerte;
