ALTER TABLE utilisateurs ADD COLUMN email VARCHAR(254);
ALTER TABLE utilisateurs ADD COLUMN annuaire_id VARCHAR(128) UNIQUE;
ALTER TABLE utilisateurs ADD COLUMN origine VARCHAR(20) NOT NULL DEFAULT 'LOCAL';
ALTER TABLE utilisateurs ALTER COLUMN mot_de_passe DROP NOT NULL;
ALTER TABLE utilisateurs ALTER COLUMN identifiant SET DATA TYPE VARCHAR(254);
UPDATE utilisateurs SET role = 'LECTEUR' WHERE role = 'GESTIONNAIRE';
-- Les droits changes imposent une nouvelle connexion.
DELETE FROM sessions_acces;
ALTER TABLE mouvements ADD COLUMN beneficiaire_id BIGINT REFERENCES utilisateurs(id);
CREATE INDEX idx_mouvement_beneficiaire ON mouvements(beneficiaire_id, date);

CREATE TABLE demandes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demandeur_id BIGINT NOT NULL REFERENCES utilisateurs(id),
    article_id BIGINT NOT NULL REFERENCES articles(id),
    quantite BIGINT NOT NULL CHECK (quantite > 0),
    motif VARCHAR(1000),
    statut VARCHAR(20) NOT NULL CHECK (statut IN ('EN_ATTENTE', 'APPROUVEE', 'REFUSEE', 'ANNULEE')),
    cree_le TIMESTAMP WITH TIME ZONE NOT NULL,
    traitee_le TIMESTAMP WITH TIME ZONE,
    traitee_par BIGINT REFERENCES utilisateurs(id),
    reponse VARCHAR(1000),
    mouvement_id BIGINT UNIQUE REFERENCES mouvements(id),
    version BIGINT
);
CREATE INDEX idx_demande_demandeur ON demandes(demandeur_id, cree_le);
CREATE INDEX idx_demande_statut ON demandes(statut, cree_le);

CREATE TABLE courriels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demande_id BIGINT NOT NULL REFERENCES demandes(id),
    destinataire VARCHAR(254) NOT NULL,
    sujet VARCHAR(200) NOT NULL,
    contenu TEXT NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE NOT NULL,
    envoye_le TIMESTAMP WITH TIME ZONE,
    prochaine_tentative TIMESTAMP WITH TIME ZONE NOT NULL,
    tentatives INTEGER NOT NULL DEFAULT 0,
    derniere_erreur VARCHAR(500)
);
CREATE INDEX idx_courriel_attente ON courriels(envoye_le, prochaine_tentative);
