package com.ga.gestionstock.entity;
public enum Permission {
    VOIR_TABLEAU_BORD, GERER_ARTICLES, GERER_STOCK, TRAITER_DEMANDES,
    VOIR_MOUVEMENTS, GERER_ALERTES, EXPORTER_STOCK, GERER_NOTIFICATIONS
}
